Repository hoanghm/Proact, pull requests merged in 2024-06, with the labels that each got.

#33 frontend gemini api
  .gitignore
  README.md
  firebase.json
  gemini_proact_flutter/lib/main.dart
  gemini_proact_flutter/pubspec.lock
  gemini_proact_flutter/pubspec.yaml
  gemini_proact_server/Dockerfile
  gemini_proact_server/cli_wrapper.py
  gemini_proact_server/gemini_client.py
  gemini_proact_server/main.py
  gemini_proact_server/misc.py
  gemini_proact_server/requirements.txt
  gemini_proact_server/web_server.py
Labels: gemini-api, infra

#37 Register app integrations in firebase, configure android build
  README.md
  gemini_proact_flutter/android/app/build.gradle
  gemini_proact_flutter/android/app/google-services.json
  gemini_proact_flutter/android/app/src/main/kotlin/com/proact/MainActivity.kt
  gemini_proact_flutter/android/gradle.properties
  gemini_proact_flutter/android/gradle/wrapper/gradle-wrapper.properties
  gemini_proact_flutter/android/settings.gradle
  gemini_proact_flutter/firebase.json
  gemini_proact_flutter/ios/Flutter/Debug.xcconfig
  gemini_proact_flutter/ios/Flutter/Release.xcconfig
  gemini_proact_flutter/ios/Podfile
  gemini_proact_flutter/ios/Podfile.lock
  gemini_proact_flutter/ios/Runner.xcodeproj/project.pbxproj
  gemini_proact_flutter/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  gemini_proact_flutter/ios/Runner.xcworkspace/contents.xcworkspacedata
  gemini_proact_flutter/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  gemini_proact_flutter/ios/Runner/GoogleService-Info.plist
  gemini_proact_flutter/ios/Runner/Info.plist
  gemini_proact_flutter/lib/firebase_options.dart
  gemini_proact_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  gemini_proact_flutter/macos/Runner.xcodeproj/project.pbxproj
  gemini_proact_flutter/macos/Runner/Configs/AppInfo.xcconfig
  gemini_proact_flutter/macos/Runner/GoogleService-Info.plist
  gemini_proact_flutter/pubspec.lock
  gemini_proact_flutter/pubspec.yaml
  gemini_proact_flutter/windows/flutter/generated_plugin_registrant.cc
  gemini_proact_flutter/windows/flutter/generated_plugins.cmake
  gemini_proact_server/main.py
Labels: infra

#39 Fix mobile app frontend connect to internal API, gemini API
  .gitignore
  gemini_proact_flutter/lib/main.dart
  gemini_proact_flutter/lib/model/gemini_client.dart
  gemini_proact_flutter/lib/model/internal_client.dart
  gemini_proact_flutter/lib/view/home_page.dart
  gemini_proact_flutter/lib/view/root.dart
  gemini_proact_flutter/test/widget_test.dart
Labels: infra

#42 Android app build
  .gitignore
  README.md
  gemini_proact_flutter/android/app/build.gradle
  gemini_proact_flutter/android/app/google-services.json
  gemini_proact_flutter/android/app/src/main/kotlin/com/proact/MainActivity.kt
  gemini_proact_flutter/android/gradle.properties
  gemini_proact_flutter/android/gradle/wrapper/gradle-wrapper.properties
  gemini_proact_flutter/android/settings.gradle
  gemini_proact_flutter/firebase.json
  gemini_proact_flutter/ios/Flutter/Debug.xcconfig
  gemini_proact_flutter/ios/Flutter/Release.xcconfig
  gemini_proact_flutter/ios/Podfile
  gemini_proact_flutter/ios/Podfile.lock
  gemini_proact_flutter/ios/Runner.xcodeproj/project.pbxproj
  gemini_proact_flutter/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  gemini_proact_flutter/ios/Runner.xcworkspace/contents.xcworkspacedata
  gemini_proact_flutter/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  gemini_proact_flutter/ios/Runner/GoogleService-Info.plist
  gemini_proact_flutter/ios/Runner/Info.plist
  gemini_proact_flutter/lib/firebase_options.dart
  gemini_proact_flutter/lib/main.dart
  gemini_proact_flutter/lib/model/gemini_client.dart
  gemini_proact_flutter/lib/model/internal_client.dart
  gemini_proact_flutter/lib/view/home_page.dart
  gemini_proact_flutter/lib/view/root.dart
  gemini_proact_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  gemini_proact_flutter/macos/Runner.xcodeproj/project.pbxproj
  gemini_proact_flutter/macos/Runner/Configs/AppInfo.xcconfig
  gemini_proact_flutter/macos/Runner/GoogleService-Info.plist
  gemini_proact_flutter/pubspec.lock
  gemini_proact_flutter/pubspec.yaml
  gemini_proact_flutter/test/widget_test.dart
  gemini_proact_flutter/windows/flutter/generated_plugin_registrant.cc
  gemini_proact_flutter/windows/flutter/generated_plugins.cmake
  gemini_proact_server/main.py
Labels: infra

#47 Added basic UI for login signup + FirebaseAuth and CloudFirestore integration
  gemini_proact_flutter/android/app/build.gradle
  gemini_proact_flutter/lib/images/google.png
  gemini_proact_flutter/lib/main.dart
  gemini_proact_flutter/lib/view/Auth/auth_page.dart
  gemini_proact_flutter/lib/view/Home/home_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/components/my_button.dart
  gemini_proact_flutter/lib/view/Login-Signup/components/my_textfield.dart
  gemini_proact_flutter/lib/view/Login-Signup/components/square_tile.dart
  gemini_proact_flutter/lib/view/Login-Signup/login_or_signup_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/login_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/signup_page.dart
  gemini_proact_flutter/lib/view/root.dart
  gemini_proact_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  gemini_proact_flutter/pubspec.lock
  gemini_proact_flutter/pubspec.yaml
  gemini_proact_flutter/windows/flutter/generated_plugin_registrant.cc
  gemini_proact_flutter/windows/flutter/generated_plugins.cmake
Labels: frontend-ui, infra, backend

#54 Integrate login-signup with UI design
  .gitignore
  gemini_proact_flutter/lib/main.dart
  gemini_proact_flutter/lib/model/auth/login_signup.dart
  gemini_proact_flutter/lib/model/database/user.dart
  gemini_proact_flutter/lib/view/Auth/auth_page.dart
  gemini_proact_flutter/lib/view/Auth/login_signup_page.dart
  gemini_proact_flutter/lib/view/Home/gemini_client_demo_page.dart
  gemini_proact_flutter/lib/view/Home/home_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/components/my_button.dart
  gemini_proact_flutter/lib/view/Login-Signup/login_or_signup_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/login_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/signup_page.dart
  gemini_proact_flutter/lib/view/brand/proact_logo.dart
  gemini_proact_flutter/lib/view/button/primary_button.dart
  gemini_proact_flutter/lib/view/icon/square_tile.dart
  gemini_proact_flutter/lib/view/input/my_textfield.dart
  gemini_proact_flutter/lib/view/onboarding/onboarding_form.dart
  gemini_proact_flutter/lib/view/profile/profile.dart
  gemini_proact_flutter/lib/view/root.dart
  gemini_proact_flutter/lib/view/startView/start.dart
  gemini_proact_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  gemini_proact_flutter/pubspec.lock
  gemini_proact_flutter/pubspec.yaml
Labels: frontend-ui

#63 Merge login-signup #29 into onboarding #50
  .gitignore
  gemini_proact_flutter/lib/main.dart
  gemini_proact_flutter/lib/model/Onboarding/input_field_generator.dart
  gemini_proact_flutter/lib/model/auth/login_signup.dart
  gemini_proact_flutter/lib/model/database/user.dart
  gemini_proact_flutter/lib/view/Auth/auth_page.dart
  gemini_proact_flutter/lib/view/Auth/login_signup_page.dart
  gemini_proact_flutter/lib/view/Home/gemini_client_demo_page.dart
  gemini_proact_flutter/lib/view/Home/home_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/components/my_button.dart
  gemini_proact_flutter/lib/view/Login-Signup/login_or_signup_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/login_page.dart
  gemini_proact_flutter/lib/view/Login-Signup/signup_page.dart
  gemini_proact_flutter/lib/view/Onboarding/components/form_optional_add.dart
  gemini_proact_flutter/lib/view/Onboarding/components/form_page.dart
  gemini_proact_flutter/lib/view/Onboarding/components/form_toggle_button.dart
  gemini_proact_flutter/lib/view/Onboarding/onboarding_form.dart
  gemini_proact_flutter/lib/view/brand/proact_logo.dart
  gemini_proact_flutter/lib/view/button/primary_button.dart
  gemini_proact_flutter/lib/view/icon/square_tile.dart
  gemini_proact_flutter/lib/view/input/my_textfield.dart
  gemini_proact_flutter/lib/view/profile/profile.dart
  gemini_proact_flutter/lib/view/root.dart
  gemini_proact_flutter/lib/view/startView/start.dart
  gemini_proact_flutter/pubspec.lock
  gemini_proact_flutter/pubspec.yaml
Labels: frontend-ui
